print("Sunbeam")
print("Infotech")
print("Pune")
print("Karad")
print("-"*80)
print("Sunbeam",end=" ")
print("Infotech",end=" ")
print("Pune",end=" ")
print("Karad",end=" ")
print()
print("-"*80)
print("sunbeam","pune","karad",end="-",sep='*')
print("infotech",end='-')
print()
print("-"*80)
print("C","C++","Java","Python",sep='*')
print("SUNBEAM",end='-')
